Add Support for setting SSEA name
Aiven-Open/s3-connector-for-apache-kafka pull request #296
Opened 2023-08-04 08:58 UTC by ampem

This change adds support for S3 buckets enforcing Server Side Encryption.
- The feature is enabled if the config String `aws.s3.ssea.name` is set
  - valid values are `AES256` or `aws:kms` but this is a free form string in the S3 SDK

2024-01-12 17:53 UTC, jeqo requested changes
Thanks, @ampem! I think this is a valid addition to the configs.

Added some comments.

Some chores:
- Run `./gradlew checkstyleMain checkstyleTest`

To fix style related issues

2024-01-12 17:53 UTC, jeqo commented on src/main/java/io/aiven/kafka/connect/s3/config/S3SinkConfig.java
> +    public static final String AWS_S3_SSEA_NAME_CONFIG = "aws.s3.ssea.name";
Let's keep it aligned with the AWS SDK API
```suggestion
    public static final String AWS_S3_SSE_ALGORITHM_CONFIG = "aws.s3.sse.algorithm";
```
or similar. Eventually, we may need to add customer-provided keys, and piggyback on `sse` prefix .

2024-01-12 17:53 UTC, jeqo commented on src/main/java/io/aiven/kafka/connect/s3/config/S3SinkConfig.java
> +            "AWS S3 Server Side Encryption Algorithm",
docs: add sample valid values -- even though there's no strict values to validate, let's hint users what values are expected.

2024-01-12 17:53 UTC, jeqo commented on README.md
> +- To use SSE-S3 set to `AES256`
```suggestion
- To use SSE-S3 set to `AES256` or leave empty
```

2024-01-12 17:53 UTC, jeqo commented on src/test/java/io/aiven/kafka/connect/s3/S3OutputStreamTest.java
> +        assertThat(SSEA_NAME).isEqualTo(initiateMultipartUploadRequest.getObjectMetadata().getSSEAlgorithm());
nit: should we change the order this validation?
```suggestion
        assertThat(initiateMultipartUploadRequest.getObjectMetadata().getSSEAlgorithm()).isEqualTo(SSEA_NAME);
```

2024-01-16 16:17 UTC, jeqo commented on src/test/java/io/aiven/kafka/connect/s3/S3OutputStreamTest.java
> +        assertThat(initiateMultipartUploadRequest.getObjectMetadata().getContentLength()).isEqualTo(0);
nit:
```suggestion
        assertThat(initiateMultipartUploadRequest.getObjectMetadata().getContentLength()).isZero();
```

2024-01-17 10:45 UTC, ampem commented
@jeqo feedback addressed, thanks.

2024-01-17 14:54 UTC, jeqo commented on src/main/java/io/aiven/kafka/connect/s3/S3SinkTask.java
> +            fullKey, config.getAwsS3PartSize(),
nit
```suggestion
            fullKey, 
            config.getAwsS3PartSize(),
```

2024-01-17 14:55 UTC, jeqo submitted a review, later dismissed
Thanks, @ampem!
LGTM, just left a minor comment to fix format.

2024-01-17 16:51 UTC, merged